// UI <-> server DTO conversion for the design space.
//
// All field conversion lives here so React components never reshape data. The
// mapper refuses to silently drop information: a custom constraint expression
// or a non-numeric discrete level throws `MappingError` rather than producing a
// body the server would misinterpret.

import type {
  Objective,
  Parameter,
  ConstraintState,
} from '../pages/campaigns/demo-v2/types'
import type {
  ConstraintSpecInput,
  CreateCampaignRunBody,
  DesignSpaceBody,
  ObjectivePolicyInput,
  OptimizationPolicyDto,
  OptimizationPolicyInput,
  OutputSpecInput,
  ParameterSpecInput,
  RunViewDto,
  RunStatus,
  TargetSpecInput,
  AcquisitionFunction,
} from './types'

export class MappingError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'MappingError'
  }
}

// The strategy fields the frontend keeps constant across saves; the acquisition
// function is derived from the objective count, not stored here.
export interface PolicyBase {
  backendName: string
  batchSize: number
  seedPolicy: 'Fixed' | 'AutoGenerated'
  seedValue: number | null
  switchAfter: number
  initialRecommender: 'RandomRecommender' | 'FPSRecommender'
  remainSwitched: boolean
}

export const DEFAULT_POLICY_BASE: PolicyBase = {
  backendName: 'baybe',
  batchSize: 4,
  seedPolicy: 'Fixed',
  seedValue: 42,
  switchAfter: 4,
  initialRecommender: 'RandomRecommender',
  remainSwitched: true,
}

export interface DesignSpaceInputs {
  parameters: Parameter[]
  objectives: Objective[]
  constraint: ConstraintState
  policyBase: PolicyBase
}

// --- small helpers ---------------------------------------------------------

function parseFinite(raw: string, context: string): number {
  const value = Number(raw.trim())
  if (raw.trim() === '' || !Number.isFinite(value)) {
    throw new MappingError(`${context} must be a finite number (got "${raw}").`)
  }
  return value
}

function optionalText(value: string): string | undefined {
  const trimmed = value.trim()
  return trimmed === '' ? undefined : trimmed
}

// --- UI -> request body ----------------------------------------------------

function toParameterInput(param: Parameter): ParameterSpecInput {
  const unit = optionalText(param.unit)
  const description = optionalText(param.description)
  const base = {
    id: param.id,
    name: param.name.trim(),
    ...(unit === undefined ? {} : { unit }),
    ...(description === undefined ? {} : { description }),
  }

  if (param.type === 'Continuous') {
    return {
      ...base,
      type: 'Continuous',
      bounds: {
        lower: parseFinite(param.lowerBound, `Parameter "${param.name}" lower bound`),
        upper: parseFinite(param.upperBound, `Parameter "${param.name}" upper bound`),
      },
    }
  }

  const nonBlank = param.values.map((v) => v.trim()).filter((v) => v !== '')
  if (nonBlank.length === 0) {
    throw new MappingError(`Parameter "${param.name}" needs at least one value.`)
  }

  if (param.type === 'Discrete') {
    return {
      ...base,
      type: 'Discrete',
      values: nonBlank.map((raw) =>
        parseFinite(raw, `Discrete parameter "${param.name}" value`),
      ),
    }
  }

  return { ...base, type: 'Categorical', values: nonBlank }
}

function objectiveArtifacts(objectives: Objective[]): {
  outputs: OutputSpecInput[]
  targets: TargetSpecInput[]
  objectivePolicy: ObjectivePolicyInput
  acquisitionFunction: AcquisitionFunction
} {
  if (objectives.length === 0) {
    throw new MappingError('At least one objective is required.')
  }

  const outputs: OutputSpecInput[] = objectives.map((objective) => {
    const unit = optionalText(objective.unit)
    const description = optionalText(objective.description)
    return {
      id: objective.id,
      name: objective.name.trim(),
      ...(unit === undefined ? {} : { unit }),
      ...(description === undefined ? {} : { description }),
    }
  })

  // Each objective maps to one output and one target that share its id, so a
  // round-trip reconstructs the same objective deterministically.
  const targets: TargetSpecInput[] = objectives.map((objective) => ({
    id: objective.id,
    outputId: objective.id,
    direction: objective.direction,
  }))

  if (objectives.length === 1) {
    return {
      outputs,
      targets,
      objectivePolicy: { kind: 'Single', targetId: objectives[0].id },
      acquisitionFunction: 'qLogEI',
    }
  }

  return {
    outputs,
    targets,
    objectivePolicy: { kind: 'Pareto', targetIds: objectives.map((o) => o.id) },
    acquisitionFunction: 'qLogNEHVI',
  }
}

function fixedSumParameterIds(parameters: Parameter[]): string[] {
  const resin = parameters.find((p) => p.name.toLowerCase().includes('resin'))
  const hardener = parameters.find((p) => p.name.toLowerCase().includes('hardener'))
  if (resin && hardener) return [resin.id, hardener.id]
  if (parameters.length >= 2) return [parameters[0].id, parameters[1].id]
  throw new MappingError('A fixed-sum constraint needs at least two parameters.')
}

function constraintArtifacts(
  constraint: ConstraintState,
  parameters: Parameter[],
): { constraints: ConstraintSpecInput[]; constraintsConfirmed: boolean } {
  switch (constraint.choice) {
    case 'custom':
      throw new MappingError(
        'Custom constraint expressions are not supported yet and cannot be submitted. ' +
          'Choose the fixed-sum or no-constraint option instead.',
      )
    case 'fixed-sum': {
      const parameterIds = fixedSumParameterIds(parameters)
      return {
        constraints: [
          {
            kind: 'LinearEquality',
            id: 'constraint-fixed-sum',
            parameterIds,
            coefficients: [1, 1],
            rhs: 100,
          },
        ],
        constraintsConfirmed: true,
      }
    }
    case 'no-constraint':
      return { constraints: [], constraintsConfirmed: true }
    default:
      // Unresolved: savable, but validation will report it as blocking.
      return { constraints: [], constraintsConfirmed: false }
  }
}

function toOptimizationPolicyInput(
  base: PolicyBase,
  acquisitionFunction: AcquisitionFunction,
): OptimizationPolicyInput {
  return {
    backendName: base.backendName,
    batchSize: base.batchSize,
    seedPolicy: base.seedPolicy,
    seedValue: base.seedValue,
    strategyConfig: {
      kind: 'TwoPhaseMeta',
      initialRecommender: base.initialRecommender,
      switchAfter: base.switchAfter,
      remainSwitched: base.remainSwitched,
      acquisitionFunction,
    },
  }
}

export function toDesignSpaceBody(inputs: DesignSpaceInputs): DesignSpaceBody {
  const { outputs, targets, objectivePolicy, acquisitionFunction } =
    objectiveArtifacts(inputs.objectives)
  const { constraints, constraintsConfirmed } = constraintArtifacts(
    inputs.constraint,
    inputs.parameters,
  )
  return {
    parameters: inputs.parameters.map(toParameterInput),
    outputs,
    targets,
    objectivePolicy,
    constraints,
    constraintsConfirmed,
    optimizationPolicy: toOptimizationPolicyInput(inputs.policyBase, acquisitionFunction),
  }
}

export function toCreateBody(
  inputs: DesignSpaceInputs,
  meta: { name: string; goal: string | null; budgetTotal: number },
): CreateCampaignRunBody {
  return {
    ...toDesignSpaceBody(inputs),
    name: meta.name,
    goal: meta.goal,
    budgetTotal: meta.budgetTotal,
  }
}

// --- server view -> UI -----------------------------------------------------

export function extractPolicyBase(policy: OptimizationPolicyDto): PolicyBase {
  const strategy = policy.strategyConfig
  const twoPhase = strategy.kind === 'TwoPhaseMeta' ? strategy : null
  return {
    backendName: policy.backendName,
    batchSize: policy.batchSize,
    seedPolicy: policy.seedPolicy,
    seedValue: policy.seedValue,
    switchAfter: twoPhase?.switchAfter ?? DEFAULT_POLICY_BASE.switchAfter,
    initialRecommender:
      twoPhase?.initialRecommender ?? DEFAULT_POLICY_BASE.initialRecommender,
    remainSwitched: twoPhase?.remainSwitched ?? DEFAULT_POLICY_BASE.remainSwitched,
  }
}

export interface HydratedRun {
  parameters: Parameter[]
  objectives: Objective[]
  constraint: ConstraintState
  policyBase: PolicyBase
  status: RunStatus
  title: string
  goal: string
  round: number
  budgetUsed: number
  budgetTotal: number
  batchSize: number
}

export function hydrateFromView(view: RunViewDto): HydratedRun {
  const revision = view.pinnedRevision
  const run = view.campaignRun

  const parameters: Parameter[] = revision.parameters.map((param) => {
    const unit = param.unit ?? ''
    const description = param.description ?? ''
    const shared = { id: param.id, name: param.name, unit, description }
    if (param.type === 'Continuous') {
      return {
        ...shared,
        type: 'Continuous',
        lowerBound: String(param.bounds.lower),
        upperBound: String(param.bounds.upper),
      }
    }
    if (param.type === 'Discrete') {
      return { ...shared, type: 'Discrete', values: param.values.map(String) }
    }
    return { ...shared, type: 'Categorical', values: param.values }
  })

  const outputsById = new Map(view.pinnedRevision.outputs.map((o) => [o.id, o]))
  const objectives: Objective[] = revision.targets.map((target) => {
    const output = outputsById.get(target.outputId)
    return {
      id: target.id,
      name: output?.name ?? target.id,
      direction: target.direction,
      unit: output?.unit ?? '',
      description: output?.description ?? '',
    }
  })

  const constraint = hydrateConstraint(
    revision.constraints.length > 0,
    revision.constraints.some((c) => c.kind === 'LinearEquality'),
    revision.constraintsConfirmed,
  )

  return {
    parameters,
    objectives,
    constraint,
    policyBase: extractPolicyBase(run.optimizationPolicy),
    status: run.status,
    title: view.campaignDefinition.name,
    goal: view.campaignDefinition.goal ?? '',
    round: run.round,
    budgetUsed: run.budgetUsed,
    budgetTotal: run.budgetTotal,
    batchSize: run.optimizationPolicy.batchSize,
  }
}

function hydrateConstraint(
  hasAny: boolean,
  hasLinearEquality: boolean,
  confirmed: boolean,
): ConstraintState {
  if (hasLinearEquality) return { choice: 'fixed-sum', customExpression: '' }
  if (!hasAny) {
    return { choice: confirmed ? 'no-constraint' : null, customExpression: '' }
  }
  // Only fixed-sum / no-constraint are authored in this stage; any other stored
  // constraint set is treated as confirmed rather than silently dropped.
  return { choice: 'no-constraint', customExpression: '' }
}
