// UI <-> server DTO conversion for the design space.
//
// All field conversion lives here so React components never reshape data. The
// mapper refuses to silently drop information: a non-numeric discrete level
// throws `MappingError` rather than producing a body the server would
// misinterpret.

import type {
  Objective,
  Parameter,
  ConstraintState,
} from '../pages/campaigns/demo-v2/types'
import type {
  ConstraintSpecDto,
  ConstraintSpecInput,
  CreateCampaignRunBody,
  LinearEqualityConstraintDto,
  DesignSpaceBody,
  ObjectivePolicyInput,
  OptimizationPolicyDto,
  OptimizationPolicyInput,
  OutputSpecInput,
  ParameterSpecInput,
  RunViewDto,
  RunStatus,
  TargetSpecInput,
  AcquisitionFunction,
} from './types'

export class MappingError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'MappingError'
  }
}

// The strategy fields the frontend keeps constant across saves; the acquisition
// function is derived from the objective count, not stored here.
export interface PolicyBase {
  backendName: string
  batchSize: number
  seedPolicy: 'Fixed' | 'AutoGenerated'
  seedValue: number | null
  switchAfter: number
  initialRecommender: 'RandomRecommender' | 'FPSRecommender'
  remainSwitched: boolean
}

export const DEFAULT_POLICY_BASE: PolicyBase = {
  backendName: 'baybe',
  batchSize: 4,
  seedPolicy: 'Fixed',
  seedValue: 42,
  switchAfter: 4,
  initialRecommender: 'RandomRecommender',
  remainSwitched: true,
}

export interface DesignSpaceInputs {
  parameters: Parameter[]
  objectives: Objective[]
  constraint: ConstraintState
  policyBase: PolicyBase
}

// --- small helpers ---------------------------------------------------------

function parseFinite(raw: string, context: string): number {
  const value = Number(raw.trim())
  if (raw.trim() === '' || !Number.isFinite(value)) {
    throw new MappingError(`${context} must be a finite number (got "${raw}").`)
  }
  return value
}

function optionalText(value: string): string | undefined {
  const trimmed = value.trim()
  return trimmed === '' ? undefined : trimmed
}

// --- UI -> request body ----------------------------------------------------

function toParameterInput(param: Parameter): ParameterSpecInput {
  const unit = optionalText(param.unit)
  const description = optionalText(param.description)
  const base = {
    id: param.id,
    name: param.name.trim(),
    ...(unit === undefined ? {} : { unit }),
    ...(description === undefined ? {} : { description }),
  }

  if (param.type === 'Continuous') {
    return {
      ...base,
      type: 'Continuous',
      bounds: {
        lower: parseFinite(param.lowerBound, `Parameter "${param.name}" lower bound`),
        upper: parseFinite(param.upperBound, `Parameter "${param.name}" upper bound`),
      },
    }
  }

  const nonBlank = param.values.map((v) => v.trim()).filter((v) => v !== '')
  if (nonBlank.length === 0) {
    throw new MappingError(`Parameter "${param.name}" needs at least one value.`)
  }

  if (param.type === 'Discrete') {
    return {
      ...base,
      type: 'Discrete',
      values: nonBlank.map((raw) =>
        parseFinite(raw, `Discrete parameter "${param.name}" value`),
      ),
    }
  }

  return { ...base, type: 'Categorical', values: nonBlank }
}

function objectiveArtifacts(objectives: Objective[]): {
  outputs: OutputSpecInput[]
  targets: TargetSpecInput[]
  objectivePolicy: ObjectivePolicyInput
  acquisitionFunction: AcquisitionFunction
} {
  if (objectives.length === 0) {
    throw new MappingError('At least one objective is required.')
  }

  const outputs: OutputSpecInput[] = objectives.map((objective) => {
    const unit = optionalText(objective.unit)
    const description = optionalText(objective.description)
    return {
      id: objective.outputId,
      name: objective.name.trim(),
      ...(unit === undefined ? {} : { unit }),
      ...(description === undefined ? {} : { description }),
    }
  })

  // Output and target keep their own IDs (server-assigned on hydrate, freshly
  // minted for new rows) so a round-trip never rewrites what the backend stored.
  const targets: TargetSpecInput[] = objectives.map((objective) => ({
    id: objective.targetId,
    outputId: objective.outputId,
    direction: objective.direction,
  }))

  if (objectives.length === 1) {
    return {
      outputs,
      targets,
      objectivePolicy: { kind: 'Single', targetId: objectives[0].targetId },
      acquisitionFunction: 'qLogEI',
    }
  }

  return {
    outputs,
    targets,
    objectivePolicy: { kind: 'Pareto', targetIds: objectives.map((o) => o.targetId) },
    acquisitionFunction: 'qLogNEHVI',
  }
}

function fixedSumParameterIds(parameters: Parameter[]): string[] {
  const resin = parameters.find((p) => p.name.toLowerCase().includes('resin'))
  const hardener = parameters.find((p) => p.name.toLowerCase().includes('hardener'))
  if (resin && hardener) return [resin.id, hardener.id]
  if (parameters.length >= 2) return [parameters[0].id, parameters[1].id]
  throw new MappingError('A fixed-sum constraint needs at least two parameters.')
}

function constraintArtifacts(
  constraint: ConstraintState,
  parameters: Parameter[],
): { constraints: ConstraintSpecInput[]; constraintsConfirmed: boolean } {
  switch (constraint.choice) {
    case 'fixed-sum': {
      const parameterIds = fixedSumParameterIds(parameters)
      return {
        constraints: [
          {
            kind: 'LinearEquality',
            // Keep the server-assigned id/resolvedAt when hydrated; a freshly
            // authored fixed-sum carries a new stable id and a null resolvedAt.
            id: constraint.constraintId ?? 'constraint-fixed-sum',
            resolvedAt: constraint.resolvedAt ?? null,
            parameterIds,
            coefficients: [1, 1],
            rhs: 100,
          },
        ],
        constraintsConfirmed: true,
      }
    }
    case 'no-constraint':
      return { constraints: [], constraintsConfirmed: true }
    default:
      // Unresolved: savable, but validation will report it as blocking.
      return { constraints: [], constraintsConfirmed: false }
  }
}

function toOptimizationPolicyInput(
  base: PolicyBase,
  acquisitionFunction: AcquisitionFunction,
): OptimizationPolicyInput {
  return {
    backendName: base.backendName,
    batchSize: base.batchSize,
    seedPolicy: base.seedPolicy,
    seedValue: base.seedValue,
    strategyConfig: {
      kind: 'TwoPhaseMeta',
      initialRecommender: base.initialRecommender,
      switchAfter: base.switchAfter,
      remainSwitched: base.remainSwitched,
      acquisitionFunction,
    },
  }
}

export function toDesignSpaceBody(inputs: DesignSpaceInputs): DesignSpaceBody {
  const { outputs, targets, objectivePolicy, acquisitionFunction } =
    objectiveArtifacts(inputs.objectives)
  const { constraints, constraintsConfirmed } = constraintArtifacts(
    inputs.constraint,
    inputs.parameters,
  )
  return {
    parameters: inputs.parameters.map(toParameterInput),
    outputs,
    targets,
    objectivePolicy,
    constraints,
    constraintsConfirmed,
    optimizationPolicy: toOptimizationPolicyInput(inputs.policyBase, acquisitionFunction),
  }
}

export function toCreateBody(
  inputs: DesignSpaceInputs,
  meta: { name: string; goal: string | null; budgetTotal: number },
): CreateCampaignRunBody {
  return {
    ...toDesignSpaceBody(inputs),
    name: meta.name,
    goal: meta.goal,
    budgetTotal: meta.budgetTotal,
  }
}

// --- server view -> UI -----------------------------------------------------

export function extractPolicyBase(policy: OptimizationPolicyDto): PolicyBase {
  const strategy = policy.strategyConfig
  const twoPhase = strategy.kind === 'TwoPhaseMeta' ? strategy : null
  return {
    backendName: policy.backendName,
    batchSize: policy.batchSize,
    seedPolicy: policy.seedPolicy,
    seedValue: policy.seedValue,
    switchAfter: twoPhase?.switchAfter ?? DEFAULT_POLICY_BASE.switchAfter,
    initialRecommender:
      twoPhase?.initialRecommender ?? DEFAULT_POLICY_BASE.initialRecommender,
    remainSwitched: twoPhase?.remainSwitched ?? DEFAULT_POLICY_BASE.remainSwitched,
  }
}

// A concrete reason the loaded run uses a configuration this stage cannot
// express. When non-empty the page renders read-only rather than risk
// rewriting the server's config on the next save.
export interface UnsupportedReason {
  area: 'parameter' | 'objective' | 'strategy' | 'constraint'
  detail: string
}

export interface HydratedRun {
  parameters: Parameter[]
  objectives: Objective[]
  constraint: ConstraintState
  policyBase: PolicyBase
  status: RunStatus
  title: string
  goal: string
  round: number
  budgetUsed: number
  budgetTotal: number
  batchSize: number
  // Empty when the run round-trips losslessly through this stage's mapper.
  unsupported: UnsupportedReason[]
}

function hydrateParameters(specs: RunViewDto['pinnedRevision']['parameters']): Parameter[] {
  return specs.map((param) => {
    const unit = param.unit ?? ''
    const description = param.description ?? ''
    const shared = { id: param.id, name: param.name, unit, description }
    if (param.type === 'Continuous') {
      return {
        ...shared,
        type: 'Continuous',
        lowerBound: String(param.bounds.lower),
        upperBound: String(param.bounds.upper),
      }
    }
    if (param.type === 'Discrete') {
      return { ...shared, type: 'Discrete', values: param.values.map(String) }
    }
    return { ...shared, type: 'Categorical', values: param.values }
  })
}

export function hydrateFromView(view: RunViewDto): HydratedRun {
  const revision = view.pinnedRevision
  const run = view.campaignRun

  const parameters = hydrateParameters(revision.parameters)

  const outputsById = new Map(view.pinnedRevision.outputs.map((o) => [o.id, o]))
  const objectives: Objective[] = revision.targets.map((target) => {
    const output = outputsById.get(target.outputId)
    return {
      id: target.id,
      outputId: target.outputId,
      targetId: target.id,
      name: output?.name ?? target.id,
      direction: target.direction,
      unit: output?.unit ?? '',
      description: output?.description ?? '',
    }
  })

  const constraint = hydrateConstraint(revision.constraints, revision.constraintsConfirmed, parameters)

  return {
    parameters,
    objectives,
    constraint,
    policyBase: extractPolicyBase(run.optimizationPolicy),
    status: run.status,
    title: view.campaignDefinition.name,
    goal: view.campaignDefinition.goal ?? '',
    round: run.round,
    budgetUsed: run.budgetUsed,
    budgetTotal: run.budgetTotal,
    batchSize: run.optimizationPolicy.batchSize,
    unsupported: assessSupport(view),
  }
}

// The exact fixed-sum shape this stage can author: two parameters (resin +
// hardener, or the first two), unit coefficients, summing to 100.
function isStandardFixedSum(
  constraint: ConstraintSpecDto,
  parameters: Parameter[],
): boolean {
  if (constraint.kind !== 'LinearEquality') return false
  const expectedIds = fixedSumParameterIdsOrNull(parameters)
  if (expectedIds === null) return false
  return (
    arraysEqual(constraint.parameterIds, expectedIds) &&
    arraysEqual(constraint.coefficients, [1, 1]) &&
    constraint.rhs === 100
  )
}

function fixedSumParameterIdsOrNull(parameters: Parameter[]): string[] | null {
  try {
    return fixedSumParameterIds(parameters)
  } catch {
    return null
  }
}

function arraysEqual<T>(a: T[], b: T[]): boolean {
  return a.length === b.length && a.every((value, i) => value === b[i])
}

// True when both lists hold the same multiset of values (order aside).
function isPermutation<T>(a: T[], b: T[]): boolean {
  if (a.length !== b.length) return false
  const sorted = (list: T[]) => [...list].map(String).sort()
  return arraysEqual(sorted(a), sorted(b))
}

function hydrateConstraint(
  constraints: ConstraintSpecDto[],
  confirmed: boolean,
  parameters: Parameter[],
): ConstraintState {
  if (constraints.length === 0) {
    return { choice: confirmed ? 'no-constraint' : null }
  }
  if (constraints.length === 1 && confirmed && isStandardFixedSum(constraints[0], parameters)) {
    const only = constraints[0] as LinearEqualityConstraintDto
    return {
      choice: 'fixed-sum',
      constraintId: only.id,
      resolvedAt: only.resolvedAt,
    }
  }
  // Anything else is unsupported. Leave the choice unresolved rather than
  // mislabelling it as no-constraint; the page blocks editing via the
  // unsupported banner (see assessSupport).
  return { choice: null }
}

// Detect any loaded configuration this stage cannot represent. Returning a
// non-empty list puts the page in read-only mode instead of letting a save
// silently rewrite Desirability/Botorch/inequality/cardinality config down to
// the small set of shapes the editor understands.
export function assessSupport(view: RunViewDto): UnsupportedReason[] {
  const reasons: UnsupportedReason[] = []
  const revision = view.pinnedRevision
  const parameters = hydrateParameters(revision.parameters)

  for (const param of revision.parameters) {
    if (param.type === 'Continuous' && param.bounds.stepsize !== null) {
      reasons.push({
        area: 'parameter',
        detail: `Parameter "${param.name}" uses a bound stepsize, which this editor cannot express.`,
      })
    }
  }

  const policy = view.campaignRun.optimizationPolicy
  const strategy = policy.strategyConfig
  if (strategy.kind !== 'TwoPhaseMeta') {
    reasons.push({
      area: 'strategy',
      detail: `Strategy "${strategy.kind}" is not editable in this stage.`,
    })
  }

  // The objective list is one row per target, in target order, and each row
  // owns exactly one output. If the stored outputs/targets don't form that
  // one-to-one, same-order shape, a save would drop, duplicate, or reorder
  // them, so refuse to edit instead.
  const outputIds = revision.outputs.map((o) => o.id)
  const referencedOutputIds = revision.targets.map((t) => t.outputId)
  for (const target of revision.targets) {
    if (!outputIds.includes(target.outputId)) {
      reasons.push({
        area: 'objective',
        detail: `Target "${target.id}" references a missing output "${target.outputId}".`,
      })
    }
  }
  for (const output of revision.outputs) {
    const references = referencedOutputIds.filter((id) => id === output.id).length
    if (references === 0) {
      reasons.push({
        area: 'objective',
        detail: `Output "${output.id}" is not referenced by any target.`,
      })
    } else if (references > 1) {
      reasons.push({
        area: 'objective',
        detail: `Output "${output.id}" is referenced by ${references} targets.`,
      })
    }
  }
  if (isPermutation(outputIds, referencedOutputIds) && !arraysEqual(outputIds, referencedOutputIds)) {
    reasons.push({
      area: 'objective',
      detail: 'Outputs and targets are stored in a different order; this stage would reorder them on save.',
    })
  }

  const objectivePolicy = revision.objectivePolicy
  const targetIds = revision.targets.map((t) => t.id)
  if (objectivePolicy.kind === 'Desirability') {
    reasons.push({
      area: 'objective',
      detail: 'Desirability objective policy is not editable in this stage.',
    })
  } else if (objectivePolicy.kind === 'Single') {
    const expectedAcq = 'qLogEI'
    if (targetIds.length !== 1 || objectivePolicy.targetId !== targetIds[0]) {
      reasons.push({
        area: 'objective',
        detail: 'Single objective policy does not match exactly one target.',
      })
    }
    if (strategy.kind === 'TwoPhaseMeta' && strategy.acquisitionFunction !== expectedAcq) {
      reasons.push({
        area: 'strategy',
        detail: `Acquisition "${strategy.acquisitionFunction}" is not the ${expectedAcq} this stage pairs with a single objective.`,
      })
    }
  } else {
    const expectedAcq = 'qLogNEHVI'
    if (targetIds.length < 2 || !arraysEqual(objectivePolicy.targetIds, targetIds)) {
      reasons.push({
        area: 'objective',
        detail: 'Pareto objective policy does not reference every target in order.',
      })
    }
    if (strategy.kind === 'TwoPhaseMeta' && strategy.acquisitionFunction !== expectedAcq) {
      reasons.push({
        area: 'strategy',
        detail: `Acquisition "${strategy.acquisitionFunction}" is not the ${expectedAcq} this stage pairs with multiple objectives.`,
      })
    }
  }

  const constraints = revision.constraints
  if (constraints.length > 1) {
    reasons.push({
      area: 'constraint',
      detail: 'Multiple constraints are not editable in this stage.',
    })
  } else if (constraints.length === 1) {
    const only = constraints[0]
    if (!isStandardFixedSum(only, parameters)) {
      reasons.push({
        area: 'constraint',
        detail: `Constraint "${only.kind}" is not the standard fixed-sum shape this stage can edit.`,
      })
    } else if (!revision.constraintsConfirmed) {
      reasons.push({
        area: 'constraint',
        detail: 'The fixed-sum constraint is stored unconfirmed, which this editor cannot represent.',
      })
    }
  }

  return reasons
}
