// Server DTO and request-body types for the campaign-run API.
//
// These mirror the camelCase JSON the FastAPI backend serializes (see
// backend/domain/models.py). Only the shapes this stage exercises are typed;
// unused child collections (batches, rounds, measurements, logs) stay opaque.

export type Direction = 'Maximize' | 'Minimize'
export type SeedPolicy = 'Fixed' | 'AutoGenerated'
export type AcquisitionFunction = 'qLogEI' | 'qLogNEHVI' | 'qLogNParEGO'

// --- Parameter specs -------------------------------------------------------

export interface BoundsDto {
  lower: number
  upper: number
  stepsize: number | null
}

interface ParameterBaseDto {
  id: string
  name: string
  unit: string | null
  description: string | null
}

export interface ContinuousParameterDto extends ParameterBaseDto {
  type: 'Continuous'
  bounds: BoundsDto
}

export interface DiscreteParameterDto extends ParameterBaseDto {
  type: 'Discrete'
  values: number[]
}

export interface CategoricalParameterDto extends ParameterBaseDto {
  type: 'Categorical'
  values: string[]
}

export type ParameterSpecDto =
  | ContinuousParameterDto
  | DiscreteParameterDto
  | CategoricalParameterDto

// --- Output / target / objective ------------------------------------------

export interface OutputSpecDto {
  id: string
  name: string
  unit: string | null
  description: string | null
}

export interface TargetSpecDto {
  id: string
  outputId: string
  direction: Direction
  targetValue: number | null
}

export type ObjectivePolicyDto =
  | { kind: 'Single'; targetId: string }
  | { kind: 'Pareto'; targetIds: string[] }
  | { kind: 'Desirability'; [key: string]: unknown }

// --- Constraints -----------------------------------------------------------

export interface LinearEqualityConstraintDto {
  kind: 'LinearEquality'
  id: string
  resolvedAt: string | null
  parameterIds: string[]
  coefficients: number[]
  rhs: number
}

export type ConstraintSpecDto =
  | LinearEqualityConstraintDto
  | { kind: 'LinearInequality'; [key: string]: unknown }
  | { kind: 'Cardinality'; [key: string]: unknown }

// --- Optimization policy ---------------------------------------------------

export type StrategyConfigDto =
  | {
      kind: 'TwoPhaseMeta'
      initialRecommender: 'RandomRecommender' | 'FPSRecommender'
      switchAfter: number
      remainSwitched: boolean
      acquisitionFunction: AcquisitionFunction
    }
  | { kind: 'Botorch'; acquisitionFunction: AcquisitionFunction }

export interface OptimizationPolicyDto {
  id: string
  backendName: string
  batchSize: number
  seedPolicy: SeedPolicy
  seedValue: number | null
  strategyConfig: StrategyConfigDto
}

// --- Aggregate view --------------------------------------------------------

export interface CampaignDefinitionDto {
  id: string
  name: string
  goal: string | null
  headRevisionId: string
  createdAt: string
  createdBy: string
  updatedAt: string
}

export interface RevisionDto {
  id: string
  campaignDefinitionId: string
  revisionNumber: number
  parentRevisionId: string | null
  parameters: ParameterSpecDto[]
  outputs: OutputSpecDto[]
  targets: TargetSpecDto[]
  objectivePolicy: ObjectivePolicyDto
  constraints: ConstraintSpecDto[]
  constraintsConfirmed: boolean
  constraintsConfirmedAt: string | null
  createdAt: string
  createdBy: string
}

export type RunStatus =
  | 'Draft'
  | 'DesignSpaceValidated'
  | 'RecommendationsPending'
  | 'AwaitingMeasurements'
  | 'RoundClosed'
  | 'Completed'
  | 'Archived'

export interface CampaignRunDto {
  id: string
  campaignDefinitionId: string
  definitionRevisionId: string
  status: RunStatus
  optimizationPolicy: OptimizationPolicyDto
  round: number
  budgetTotal: number
  budgetUsed: number
  createdAt: string
  updatedAt: string
  createdBy: string
}

// --- Recommendation batch / candidate ------------------------------------

export type BatchStatus = 'Proposed' | 'PartiallyExecuted' | 'FullyExecuted' | 'Superseded'

export interface EnvironmentDto {
  pythonVersion: string
  torchVersion: string
  botorchVersion: string
  dependencyLockHash: string
}

export interface AlgorithmConfigDto {
  backendName: string
  backendVersion: string
  backendCommit: string
  strategyKind: 'TwoPhaseMeta' | 'Botorch'
  hyperparameters: Record<string, unknown>
  acquisitionFunction: string
  seed: number
  environment: EnvironmentDto
}

export interface RecommendationCandidateDto {
  id: string
  parameterValues: Record<string, string | number>
  // Null for a model-free initial design; never fabricate a value from null.
  predictedMean: Record<string, number> | null
  predictedSd: Record<string, number> | null
  desirability: number | null
}

export interface RecommendationBatchDto {
  id: string
  campaignRunId: string
  roundNumber: number
  generatedAt: string
  inputSnapshot: Record<string, unknown>
  algorithmConfig: AlgorithmConfigDto
  candidates: RecommendationCandidateDto[]
  status: BatchStatus
}

// --- Experiment round / run ----------------------------------------------

export type RoundStatus = 'Open' | 'Closed'
export type ExperimentRunStatus = 'Pending' | 'Completed' | 'Failed' | 'Cancelled'

export interface ExperimentRoundDto {
  id: string
  campaignRunId: string
  roundNumber: number
  recommendationBatchId: string
  openedAt: string
  closedAt: string | null
  status: RoundStatus
}

export interface ExperimentRunDto {
  id: string
  campaignRunId: string
  experimentRoundId: string
  // Links back to the candidate this experiment realizes; null for manual runs.
  recommendationCandidateId: string | null
  parameterValues: Record<string, string | number>
  status: ExperimentRunStatus
  executedAt: string | null
  executedBy: string | null
  notes: string | null
}

export interface InitialDesignResponseDto {
  campaignRun: CampaignRunDto
  recommendationBatch: RecommendationBatchDto
  experimentRound: ExperimentRoundDto | null
  experimentRuns: ExperimentRunDto[]
}

// --- Aggregate / initial-design response ----------------------------------

export interface RunViewDto {
  campaignDefinition: CampaignDefinitionDto
  pinnedRevision: RevisionDto
  campaignRun: CampaignRunDto
  recommendationBatches: RecommendationBatchDto[]
  experimentRounds: ExperimentRoundDto[]
  experimentRuns: ExperimentRunDto[]
  measurements: unknown[]
  decisionLogs: unknown[]
}

// --- Validation ------------------------------------------------------------

export type Severity = 'blocking' | 'warning'

export interface ValidationIssueDto {
  code: string
  message: string
  severity: Severity
  relatedEntityId: string | null
}

export interface ValidationResultDto {
  ok: boolean
  issues: ValidationIssueDto[]
}

export interface ValidateResponseDto {
  validationResult: ValidationResultDto
  campaignRun: CampaignRunDto
}

export interface SaveDesignSpaceResponseDto {
  changed: boolean
  revisionChanged: boolean
  policyChanged: boolean
  view: RunViewDto
}

// --- Request bodies --------------------------------------------------------

export type ParameterSpecInput =
  | {
      type: 'Continuous'
      id: string
      name: string
      unit?: string
      description?: string
      bounds: { lower: number; upper: number }
    }
  | {
      type: 'Discrete'
      id: string
      name: string
      unit?: string
      description?: string
      values: number[]
    }
  | {
      type: 'Categorical'
      id: string
      name: string
      unit?: string
      description?: string
      values: string[]
    }

export interface OutputSpecInput {
  id: string
  name: string
  unit?: string
  description?: string
}

export interface TargetSpecInput {
  id: string
  outputId: string
  direction: Direction
}

export type ObjectivePolicyInput =
  | { kind: 'Single'; targetId: string }
  | { kind: 'Pareto'; targetIds: string[] }

export interface LinearEqualityConstraintInput {
  kind: 'LinearEquality'
  id: string
  resolvedAt: string | null
  parameterIds: string[]
  coefficients: number[]
  rhs: number
}

export type ConstraintSpecInput = LinearEqualityConstraintInput

export interface StrategyConfigInput {
  kind: 'TwoPhaseMeta'
  initialRecommender: 'RandomRecommender' | 'FPSRecommender'
  switchAfter: number
  remainSwitched: boolean
  acquisitionFunction: AcquisitionFunction
}

export interface OptimizationPolicyInput {
  backendName: string
  batchSize: number
  seedPolicy: SeedPolicy
  seedValue: number | null
  strategyConfig: StrategyConfigInput
}

export interface DesignSpaceBody {
  parameters: ParameterSpecInput[]
  outputs: OutputSpecInput[]
  targets: TargetSpecInput[]
  objectivePolicy: ObjectivePolicyInput
  constraints: ConstraintSpecInput[]
  constraintsConfirmed: boolean
  optimizationPolicy: OptimizationPolicyInput
}

export interface CreateCampaignRunBody extends DesignSpaceBody {
  name: string
  goal: string | null
  budgetTotal: number
}
